name: flutter_email
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.3.4
  flutter_quill: ^10.8.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  intl: ^0.19.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  universal_html: ^2.2.4
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  video_player: ^2.9.2
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:

flutter:
  uses-material-design: true
  generate: true
  fonts:
  - family: monospace
    fonts:
      - asset: assets/fonts/IBMPlexMono-Regular.ttf
  - family: serif
    fonts:
      - asset: assets/fonts/RobotoSerif_28pt-Regular.ttf
  - family: sans-serif
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
  - family: ibarra-real-nova
    fonts:
        - asset: assets/fonts/IbarraRealNova-Regular.ttf
  - family: square-peg
    fonts:
      - asset: assets/fonts/SquarePeg-Regular.ttf
  - family: nunito
    fonts:
      - asset: assets/fonts/Nunito-Regular.ttf
  - family: pacifico
    fonts:
      - asset: assets/fonts/Pacifico-Regular.ttf
  - family: roboto-mono
    fonts:
      - asset: assets/fonts/RobotoMono-Regular.ttf

assets:
  - assets/placeholder.jpg
  - assets/mock.json